#!/bin/sh -e

<<<<<<<< HEAD:debian/linux-image-6.5.0-kali6-armmp.prerm
version=6.5.0-kali6-armmp
========
version=6.6.9-cloud-arm64
>>>>>>>> debian:debian/linux-image-6.6.9-cloud-arm64-unsigned.prerm
image_path=/boot/vmlinuz-$version

if [ "$1" != remove ]; then
    exit 0
fi

linux-check-removal $version

if [ -d /etc/kernel/prerm.d ]; then
    DEB_MAINT_PARAMS="$*" run-parts --report --exit-on-error --arg=$version \
	      --arg=$image_path /etc/kernel/prerm.d
fi

exit 0
