#!/bin/sh -e

<<<<<<<< HEAD:debian/linux-image-6.4.0-kali2-riscv64.prerm
version=6.4.0-kali2-riscv64
========
version=6.4.0-3-riscv64
>>>>>>>> debian:debian/linux-image-6.4.0-3-riscv64.prerm
image_path=/boot/vmlinux-$version

if [ "$1" != remove ]; then
    exit 0
fi

linux-check-removal $version

if [ -d /etc/kernel/prerm.d ]; then
    DEB_MAINT_PARAMS="$*" run-parts --report --exit-on-error --arg=$version \
	      --arg=$image_path /etc/kernel/prerm.d
fi

exit 0
