#!/bin/sh -e

<<<<<<<< HEAD:debian/linux-image-6.0.0-kali5-686.prerm
version=6.0.0-kali5-686
========
version=6.0.0-6-686
>>>>>>>> debian:debian/linux-image-6.0.0-6-686-unsigned.prerm
image_path=/boot/vmlinuz-$version

if [ "$1" != remove ]; then
    exit 0
fi

linux-check-removal $version

if [ -d /etc/kernel/prerm.d ]; then
    DEB_MAINT_PARAMS="$*" run-parts --report --exit-on-error --arg=$version \
	      --arg=$image_path /etc/kernel/prerm.d
fi

exit 0
