#!/bin/sh -e

<<<<<<<< HEAD:debian/linux-image-5.19.0-kali2-octeon.prerm
version=5.19.0-kali2-octeon
========
version=6.0.0-2-octeon
>>>>>>>> debian:debian/linux-image-6.0.0-2-octeon.prerm
image_path=/boot/vmlinux-$version

if [ "$1" != remove ]; then
    exit 0
fi

linux-check-removal $version

if [ -d /etc/kernel/prerm.d ]; then
    DEB_MAINT_PARAMS="$*" run-parts --report --exit-on-error --arg=$version \
	      --arg=$image_path /etc/kernel/prerm.d
fi

exit 0
