#!/bin/sh -e

<<<<<<<< HEAD:debian/linux-image-6.1.0-kali7-powerpc.prerm
version=6.1.0-kali7-powerpc
========
version=6.1.0-9-powerpc-smp
>>>>>>>> debian:debian/linux-image-6.1.0-9-powerpc-smp.prerm
image_path=/boot/vmlinux-$version

if [ "$1" != remove ]; then
    exit 0
fi

linux-check-removal $version

if [ -d /etc/kernel/prerm.d ]; then
    DEB_MAINT_PARAMS="$*" run-parts --report --exit-on-error --arg=$version \
	      --arg=$image_path /etc/kernel/prerm.d
fi

exit 0
