#!/bin/sh -e

<<<<<<<< HEAD:debian/linux-image-6.5.0-kali3-armmp.prerm
version=6.5.0-kali3-armmp
========
version=6.5.0-3-5kc-malta
>>>>>>>> debian:debian/linux-image-6.5.0-3-5kc-malta.prerm
image_path=/boot/vmlinuz-$version

if [ "$1" != remove ]; then
    exit 0
fi

linux-check-removal $version

if [ -d /etc/kernel/prerm.d ]; then
    DEB_MAINT_PARAMS="$*" run-parts --report --exit-on-error --arg=$version \
	      --arg=$image_path /etc/kernel/prerm.d
fi

exit 0
